// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Riddim.Services;

namespace Riddim.Migrations
{
    [DbContext(typeof(RiddimDbContext))]
    partial class RiddimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Riddim.Data.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_room_name");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Riddim.Data.Domain.RoomSlug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("primary");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_roomslug");

                    b.HasIndex("RoomId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_roomslug_slug");

                    b.ToTable("roomslugs");
                });

            modelBuilder.Entity("Riddim.Data.Domain.RoomSlug", b =>
                {
                    b.HasOne("Riddim.Data.Domain.Room", "Room")
                        .WithMany("Slugs")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("fk_roomslug_room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Riddim.Data.Domain.Room", b =>
                {
                    b.Navigation("Slugs");
                });
#pragma warning restore 612, 618
        }
    }
}
